from dataclasses import dataclass, field
from typing import List

@dataclass
class ApplicationConfig:
    project_uuid: str
    server_uuid: str
    environment_name: str
    environment_uuid: str
    git_repository: str
    git_branch: str
    build_pack: str
    ports_exposes: str
    destination_uuid: str
    name: str
    description: str
    domains: str
    git_commit_sha: str
    docker_registry_image_name: str
    docker_registry_image_tag: str
    is_static: bool
    static_image: str
    install_command: str
    build_command: str
    start_command: str
    ports_mappings: str
    base_directory: str
    publish_directory: str
    health_check_enabled: bool
    health_check_path: str
    health_check_port: str
    health_check_host: str
    health_check_method: str
    health_check_return_code: int
    health_check_scheme: str
    health_check_response_text: str
    health_check_interval: int
    health_check_timeout: int
    health_check_retries: int
    health_check_start_period: int
    limits_memory: str
    limits_memory_swap: str
    limits_memory_swappiness: int
    limits_memory_reservation: str
    limits_cpus: str
    limits_cpuset: str
    limits_cpu_shares: int
    custom_labels: str
    custom_docker_run_options: str
    post_deployment_command: str
    post_deployment_command_container: str
    pre_deployment_command: str
    pre_deployment_command_container: str
    manual_webhook_secret_github: str
    manual_webhook_secret_gitlab: str
    manual_webhook_secret_bitbucket: str
    manual_webhook_secret_gitea: str
    redirect: str
    instant_deploy: bool
    dockerfile: str
    docker_compose_location: str
    docker_compose_raw: str
    docker_compose_custom_start_command: str
    docker_compose_custom_build_command: str
    docker_compose_domains: List[str]
    watch_paths: str
    use_build_server: bool
    is_http_basic_auth_enabled: bool
    http_basic_auth_username: str
    http_basic_auth_password: str
    connect_to_docker_network: bool
